---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing kubectl on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_kubectl_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "kubectl is defined"
  tags:
    - "kubectl"
- name: "Install kubectl"
  package:
    pkg: "{{ install_kubectl_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "kubectl is defined"
  tags:
    - "kubectl"
